import type { Exercise } from '@/types/exercise'

export const exercises: Exercise[] = [
  // === SALUD VISUAL ===
  {
    id: 'visual-diagonal',
    category: 'visual',
    name: 'Movimientos diagonales de ojos',
    description: 'Ejercicio ocular que fortalece los musculos extraoculares y reduce la fatiga visual por pantalla.',
    benefits: 'Alivia la tension ocular, mejora la flexibilidad de los musculos del ojo y previene el sindrome de vision por computador.',
    steps: [
      { instruction: 'Sientese derecho y mire al frente. Sin mover la cabeza, dirija la mirada hacia la esquina superior derecha.', durationSeconds: 5 },
      { instruction: 'Lentamente mueva la mirada en diagonal hacia la esquina inferior izquierda.', durationSeconds: 5 },
      { instruction: 'Ahora dirija la mirada hacia la esquina superior izquierda.', durationSeconds: 5 },
      { instruction: 'Mueva la mirada lentamente hacia la esquina inferior derecha. Repita el ciclo completo.', durationSeconds: 5, repetitions: 5 },
    ],
    totalDurationSeconds: 120,
    illustration: 'visual-diagonal',
    difficulty: 'facil',
  },
  {
    id: 'visual-parpadeo',
    category: 'visual',
    name: 'Parpadeo consciente',
    description: 'Parpadeo voluntario y constante para humectar la superficie ocular.',
    benefits: 'Previene la resequedad ocular causada por la reduccion del parpadeo frente a pantallas (de 15 a 5 veces por minuto).',
    steps: [
      { instruction: 'Cierre los ojos suavemente durante 2 segundos, luego abralos. Repita de forma ritmica.', durationSeconds: 30, repetitions: 15 },
      { instruction: 'Ahora parpadee rapidamente 20 veces seguidas de forma suave.', durationSeconds: 20 },
      { instruction: 'Cierre los ojos con fuerza durante 5 segundos, luego relajelos. Repita 5 veces.', durationSeconds: 30 },
    ],
    totalDurationSeconds: 80,
    illustration: 'visual-parpadeo',
    difficulty: 'facil',
  },
  {
    id: 'visual-palming',
    category: 'visual',
    name: 'Palming (descanso visual)',
    description: 'Tecnica de relajacion ocular cubriendo los ojos con las palmas de las manos.',
    benefits: 'Relaja los musculos oculares, reduce la fatiga visual y proporciona oscuridad total para descansar la retina.',
    steps: [
      { instruction: 'Frote las palmas de sus manos una contra otra durante 10 segundos para generar calor.', durationSeconds: 10 },
      { instruction: 'Cubra ambos ojos con las palmas ahuecadas sin presionar los globos oculares. Respire profundamente.', durationSeconds: 60 },
      { instruction: 'Mantenga los ojos cerrados bajo las palmas. Visualice oscuridad total. Relaje los hombros.', durationSeconds: 60 },
    ],
    totalDurationSeconds: 130,
    illustration: 'visual-palming',
    difficulty: 'facil',
  },

  // === CUELLO Y HOMBROS ===
  {
    id: 'cuello-lateral',
    category: 'cuello_hombros',
    name: 'Inclinacion lateral del cuello',
    description: 'Estiramiento suave de los musculos laterales del cuello (escalenos y esternocleidomastoideo).',
    benefits: 'Alivia la tension cervical, reduce rigidez y previene dolores de cabeza tensionales.',
    steps: [
      { instruction: 'Sientese derecho. Incline lentamente la cabeza hacia el hombro derecho. Mantenga 15 segundos.', durationSeconds: 15 },
      { instruction: 'Vuelva al centro lentamente.', durationSeconds: 3 },
      { instruction: 'Incline la cabeza hacia el hombro izquierdo. Mantenga 15 segundos.', durationSeconds: 15 },
      { instruction: 'Vuelva al centro. Repita el ciclo completo.', durationSeconds: 3, repetitions: 4 },
    ],
    totalDurationSeconds: 144,
    illustration: 'cuello-lateral',
    difficulty: 'facil',
  },
  {
    id: 'cuello-rotacion',
    category: 'cuello_hombros',
    name: 'Rotacion suave del cuello',
    description: 'Movimiento circular controlado para liberar tension en todas las direcciones del cuello.',
    benefits: 'Mejora la movilidad cervical, reduce la rigidez y promueve la circulacion en la zona.',
    steps: [
      { instruction: 'Baje la barbilla hacia el pecho suavemente.', durationSeconds: 5 },
      { instruction: 'Gire lentamente la cabeza hacia la derecha describiendo un semicirculo. No vaya hacia atras.', durationSeconds: 10 },
      { instruction: 'Regrese por el mismo camino hacia la izquierda describiendo otro semicirculo.', durationSeconds: 10 },
      { instruction: 'Repita el movimiento de forma fluida, siempre por delante, nunca hacia atras.', durationSeconds: 10, repetitions: 5 },
    ],
    totalDurationSeconds: 135,
    illustration: 'cuello-rotacion',
    difficulty: 'facil',
  },
  {
    id: 'hombros-rotacion',
    category: 'cuello_hombros',
    name: 'Rotacion de hombros hacia atras',
    description: 'Circulos amplios con los hombros para liberar tension del trapecio.',
    benefits: 'Alivia la tension acumulada en hombros y parte superior de la espalda por la postura de escritorio.',
    steps: [
      { instruction: 'Con los brazos relajados a los lados, eleve ambos hombros hacia las orejas.', durationSeconds: 5 },
      { instruction: 'Lleve los hombros hacia atras abriendo el pecho.', durationSeconds: 5 },
      { instruction: 'Baje los hombros completamente, relajando.', durationSeconds: 5 },
      { instruction: 'Complete el circulo llevando los hombros hacia adelante. Repita hacia atras.', durationSeconds: 5, repetitions: 10 },
    ],
    totalDurationSeconds: 120,
    illustration: 'hombros-rotacion',
    difficulty: 'facil',
  },
  {
    id: 'hombros-encogimiento',
    category: 'cuello_hombros',
    name: 'Encogimiento y liberacion de hombros',
    description: 'Contraccion y relajacion progresiva de los musculos del trapecio superior.',
    benefits: 'Tecnica de relajacion muscular progresiva que reduce la tension acumulada y el estres.',
    steps: [
      { instruction: 'Suba ambos hombros lo mas alto posible hacia las orejas. Mantenga la tension 5 segundos.', durationSeconds: 5 },
      { instruction: 'Deje caer los hombros de golpe, soltando toda la tension. Sienta la diferencia.', durationSeconds: 5 },
      { instruction: 'Respire profundamente. Repita el ciclo de tension y relajacion.', durationSeconds: 5, repetitions: 8 },
    ],
    totalDurationSeconds: 120,
    illustration: 'hombros-encogimiento',
    difficulty: 'facil',
  },

  // === MANOS Y MUNECAS ===
  {
    id: 'manos-abanico',
    category: 'manos_munecas',
    name: 'Estiramiento en abanico de dedos',
    description: 'Apertura y cierre de los dedos en extension maxima como un abanico.',
    benefits: 'Estira los tendones flexores, previene el sindrome del tunel carpiano y mejora la circulacion en las manos.',
    steps: [
      { instruction: 'Extienda ambas manos frente a usted con las palmas hacia abajo.', durationSeconds: 5 },
      { instruction: 'Abra los dedos separandolos al maximo, como un abanico. Mantenga 5 segundos.', durationSeconds: 5 },
      { instruction: 'Cierre los dedos formando un puno suave. Mantenga 5 segundos.', durationSeconds: 5 },
      { instruction: 'Repita la apertura y cierre de forma ritmica.', durationSeconds: 5, repetitions: 10 },
    ],
    totalDurationSeconds: 120,
    illustration: 'manos-abanico',
    difficulty: 'facil',
  },
  {
    id: 'manos-flexion',
    category: 'manos_munecas',
    name: 'Flexion y extension de munecas',
    description: 'Estiramiento de los musculos flexores y extensores del antebrazo.',
    benefits: 'Previene la tendinitis, el sindrome del tunel carpiano y reduce la rigidez por uso prolongado del teclado y raton.',
    steps: [
      { instruction: 'Extienda el brazo derecho con la palma hacia arriba. Con la mano izquierda, tire suavemente los dedos hacia abajo. Mantenga 15 segundos.', durationSeconds: 15 },
      { instruction: 'Ahora gire la palma hacia abajo y tire los dedos hacia usted. Mantenga 15 segundos.', durationSeconds: 15 },
      { instruction: 'Repita ambos estiramientos con el brazo izquierdo.', durationSeconds: 30 },
      { instruction: 'Sacuda ambas manos suavemente durante 10 segundos para relajar.', durationSeconds: 10 },
    ],
    totalDurationSeconds: 70,
    illustration: 'manos-flexion',
    difficulty: 'facil',
  },
  {
    id: 'manos-circulos',
    category: 'manos_munecas',
    name: 'Circulos de muneca',
    description: 'Rotacion completa de las munecas en ambas direcciones.',
    benefits: 'Mejora la lubricacion articular, previene la rigidez y promueve la circulacion en munecas y manos.',
    steps: [
      { instruction: 'Extienda ambos brazos frente a usted y cierre los punos suavemente.', durationSeconds: 5 },
      { instruction: 'Gire ambas munecas en circulos amplios hacia la derecha. Haga 10 circulos.', durationSeconds: 20 },
      { instruction: 'Cambie de direccion y gire hacia la izquierda. Haga 10 circulos.', durationSeconds: 20 },
      { instruction: 'Sacuda las manos relajando toda tension.', durationSeconds: 10 },
    ],
    totalDurationSeconds: 55,
    illustration: 'manos-circulos',
    difficulty: 'facil',
  },

  // === ESPALDA ===
  {
    id: 'espalda-rotacion',
    category: 'espalda',
    name: 'Rotacion del tronco en silla',
    description: 'Giro controlado del torso manteniendo las caderas fijas para estirar la columna.',
    benefits: 'Alivia la rigidez lumbar y dorsal, mejora la movilidad de la columna y reduce el dolor por sedentarismo.',
    steps: [
      { instruction: 'Sientese derecho con los pies firmes en el suelo. Cruce los brazos sobre el pecho.', durationSeconds: 5 },
      { instruction: 'Gire lentamente el tronco hacia la derecha mirando por encima del hombro. Mantenga 15 segundos.', durationSeconds: 15 },
      { instruction: 'Vuelva al centro lentamente.', durationSeconds: 3 },
      { instruction: 'Gire hacia la izquierda mirando por encima del hombro. Mantenga 15 segundos. Repita el ciclo.', durationSeconds: 15, repetitions: 4 },
    ],
    totalDurationSeconds: 152,
    illustration: 'espalda-rotacion',
    difficulty: 'facil',
  },
  {
    id: 'espalda-encorvamiento',
    category: 'espalda',
    name: 'Encorvamiento controlado en silla',
    description: 'Flexion vertebral progresiva para estirar la musculatura paravertebral.',
    benefits: 'Estira los musculos erectores de la columna, alivia la compresion discal y reduce la tension lumbar.',
    steps: [
      { instruction: 'Sientese en el borde de la silla con los pies firmes en el suelo.', durationSeconds: 5 },
      { instruction: 'Baje lentamente la cabeza, luego los hombros, luego la espalda, vertebra por vertebra, hasta que el torso cuelgue entre las piernas.', durationSeconds: 15 },
      { instruction: 'Mantenga la posicion. Respire profundamente 5 veces sintiendo como se estira la espalda.', durationSeconds: 30 },
      { instruction: 'Suba lentamente, vertebra por vertebra, hasta quedar sentado derecho. Repita.', durationSeconds: 15, repetitions: 3 },
    ],
    totalDurationSeconds: 135,
    illustration: 'espalda-encorvamiento',
    difficulty: 'moderado',
  },
  {
    id: 'espalda-gato',
    category: 'espalda',
    name: 'Estiramiento de gato sentado',
    description: 'Adaptacion del estiramiento de gato/vaca de yoga para realizar sentado en la silla de oficina.',
    benefits: 'Moviliza toda la columna vertebral, alivia la tension dorsal y mejora la postura.',
    steps: [
      { instruction: 'Sientese derecho con las manos sobre las rodillas.', durationSeconds: 5 },
      { instruction: 'Arquee la espalda hacia adelante sacando pecho y mirando hacia arriba (posicion de vaca). Mantenga 10 segundos.', durationSeconds: 10 },
      { instruction: 'Redondee la espalda metiendo la barbilla al pecho y empujando la columna hacia atras (posicion de gato). Mantenga 10 segundos.', durationSeconds: 10 },
      { instruction: 'Alterne entre ambas posiciones de forma fluida.', durationSeconds: 10, repetitions: 6 },
    ],
    totalDurationSeconds: 145,
    illustration: 'espalda-gato',
    difficulty: 'facil',
  },
]
